language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: example/build
  on:
    branch: master
